In [5]:
import pandas as pd
from generate_features import generate_features

In [6]:
usd_eur = pd.read_csv("./USDEUR=X.csv", parse_dates=['Date'])
usd_gbp = pd.read_csv("./USDGBP=X.csv", parse_dates=['Date'])
usd_chf = pd.read_csv("./USDCHF=X.csv", parse_dates=['Date'])
eur_gbp = pd.read_csv("./EURGBP=X.csv", parse_dates=['Date'])
eur_chf = pd.read_csv("./EURCHF=X.csv", parse_dates=['Date'])
gbp_chf = pd.read_csv("./GBPCHF=X.csv", parse_dates=['Date'])
print(f"USD/EUR: {usd_eur.shape}")
display(usd_eur.head())
print(f"USD/GBP: {usd_gbp.shape}")
display(usd_gbp.head())
print(f"USD/CHF: {usd_chf.shape}")
display(usd_chf.head())
print(f"EUR/GBP: {eur_gbp.shape}")
display(eur_gbp.head())
print(f"EUR/CHF: {eur_chf.shape}")
display(eur_chf.head())
print(f"GBP/CHF: {gbp_chf.shape}")
display(gbp_chf.head())

USD/EUR: (282, 7)

        Date     Open     High      Low    Close  Adj Close  Volume
0 2022-09-30  1.01734  1.02711  1.01523  1.01734    1.01734       0
1 2022-10-03  1.02117  1.02526  1.01582  1.02117    1.02117       0
2 2022-10-04  1.01708  1.01971  1.00199  1.01708    1.01708       0
3 2022-10-05  1.00157  1.01673  1.00058  1.00157    1.00157       0
4 2022-10-06  1.00898  1.02152  1.00742  1.00898    1.00898       0

USD/GBP: (282, 7)

        Date     Open     High      Low    Close  Adj Close  Volume
0 2022-09-30  0.89591  0.90688  0.89016  0.89530    0.89530       0
1 2022-10-03  0.89795  0.90188  0.88243  0.89762    0.89762       0
2 2022-10-04  0.88186  0.88635  0.87367  0.88229    0.88229       0
3 2022-10-05  0.87332  0.89065  0.86995  0.87326    0.87326       0
4 2022-10-06  0.88060  0.89925  0.87847  0.88064    0.88064       0

USD/CHF: (282, 7)

        Date     Open     High      Low    Close  Adj Close  Volume
0 2022-09-30  0.97493  0.98514  0.97395  0.97493    0.97493       0
1 2022-10-03  0.98565  0.99314  0.98351  0.98565    0.98565       0
2 2022-10-04  0.99256  0.99408  0.97948  0.99256    0.99256       0
3 2022-10-05  0.97869  0.98883  0.97844  0.97869    0.97869       0
4 2022-10-06  0.98132  0.99133  0.97790  0.98132    0.98132       0

EUR/GBP: (282, 7)

        Date     Open     High      Low    Close  Adj Close  Volume
0 2022-09-30  0.88002  0.88469  0.87530  0.88002    0.88002       0
1 2022-10-03  0.87895  0.88302  0.86776  0.87895    0.87895       0
2 2022-10-04  0.86740  0.87415  0.86506  0.86740    0.86740       0
3 2022-10-05  0.87183  0.87761  0.86945  0.87183    0.87183       0
4 2022-10-06  0.87252  0.88144  0.87175  0.87252    0.87252       0

EUR/CHF: (282, 7)

        Date     Open     High      Low    Close  Adj Close  Volume
0 2022-09-30  0.95826  0.96420  0.95500  0.95826    0.95826       0
1 2022-10-03  0.96513  0.97646  0.96430  0.96513    0.96513       0
2 2022-10-04  0.97578  0.97984  0.97390  0.97578    0.97578       0
3 2022-10-05  0.97714  0.97961  0.97043  0.97714    0.97714       0
4 2022-10-06  0.97264  0.97379  0.96920  0.97264    0.97264       0

GBP/CHF: (282, 7)

        Date     Open     High      Low    Close  Adj Close  Volume
0 2022-09-30  1.08868  1.09890  1.08095  1.08868    1.08868       0
1 2022-10-03  1.09778  1.12295  1.09302  1.09778    1.09778       0
2 2022-10-04  1.12474  1.12827  1.11793  1.12474    1.12474       0
3 2022-10-05  1.12057  1.12641  1.10700  1.12057    1.12057       0
4 2022-10-06  1.11404  1.11585  1.10107  1.11404    1.11404       0

In [7]:
usd_eur_feats = generate_features(usd_eur)
print(f"USD/EUR Features shape: {usd_eur_feats.shape}")
display(usd_eur_feats.head())

usd_gbp_feats = generate_features(usd_gbp)
print(f"USD/GBP Features shape: {usd_gbp_feats.shape}")
display(usd_gbp_feats.head())

usd_chf_feats = generate_features(usd_chf)
print(f"USD/CHF Features shape: {usd_chf_feats.shape}")
display(usd_chf_feats.head())

eur_gbp_feats = generate_features(eur_gbp)
print(f"EUR/GBP Features shape: {eur_gbp_feats.shape}")
display(eur_gbp_feats.head())

eur_chf_feats = generate_features(eur_chf)
print(f"EUR/CHF Features shape: {eur_chf_feats.shape}")
display(eur_chf_feats.head())

gbp_chf_feats = generate_features(gbp_chf)
print(f"GBP/CHF Features shape: {gbp_chf_feats.shape}")
display(gbp_chf_feats.head())

USD/EUR Features shape: (261, 28)

,Date,opt_sine_offset,opt_sine_amp,opt_sine_freq,opt_sine_phase,opt_fourier_offset,opt_fourier_cosamp,opt_fourier_cosfreq,opt_fourier_cosphase,opt_fourier_sinamp,...,ROC1,ROC5,ROC20,WILLIAMS14,RSI14,CMO9,DEMA9,TEMA9,STOCH14,Close
0,2023-10-30,0.943330,1.0,0.999855,0.002468,0.945102,-0.003343,1.135882,-0.487341,-0.002250,...,0.367014,39.191880,1.233947,-5453.382921,54.178000,6.782266,0.006951,0.007082,54.178000,0.94660
1,2023-10-27,0.943382,1.0,1.000125,-0.001452,0.944744,-0.001989,1.192463,-2.966973,-0.001240,...,3.154941,31.753308,-2.154636,-5453.556132,54.143665,6.682299,0.006335,0.006185,54.143665,0.94657
2,2023-10-26,0.943288,1.0,0.999911,0.002938,0.944439,0.203395,0.974242,1.238721,0.202557,...,46.360618,-24.561889,-41.320851,-5454.999550,53.876225,5.925654,0.005504,0.004857,53.876225,0.94632
3,2023-10-25,0.944567,1.0,0.999601,0.000482,0.944003,-0.302393,1.163001,0.720152,0.300439,...,-560.411327,-26.877080,-29.906482,-5146.098329,51.224183,-1.511742,0.004498,0.003084,51.224183,0.94381
4,2023-10-24,0.946045,1.0,0.999835,0.001881,0.943493,-0.255850,0.917888,0.664509,-0.256347,...,-119.950906,-112.944869,-120.471901,-5181.855247,43.272136,-24.831765,0.004395,0.002398,43.272136,0.93722

USD/GBP Features shape: (261, 28)

,Date,opt_sine_offset,opt_sine_amp,opt_sine_freq,opt_sine_phase,opt_fourier_offset,opt_fourier_cosamp,opt_fourier_cosfreq,opt_fourier_cosphase,opt_fourier_sinamp,...,ROC1,ROC5,ROC20,WILLIAMS14,RSI14,CMO9,DEMA9,TEMA9,STOCH14,Close
0,2023-10-30,0.822007,1.000000,0.999801,0.001999,0.819218,0.190039,1.078621,0.525351,0.190820,...,17.160133,57.033048,147.884604,-4596.817396,58.985827,16.977313,0.007692,0.008011,58.985827,0.82515
1,2023-10-27,0.822157,1.000000,1.000142,-0.000905,0.818568,0.001722,0.949024,2.165012,-0.000506,...,-24.212879,0.139708,175.919669,-4603.712015,57.736859,13.465413,0.006917,0.007140,57.736859,0.82392
2,2023-10-26,0.821360,1.000000,1.000162,0.000230,0.817936,-0.316034,1.003077,0.842109,-0.316410,...,72.342595,40.369400,29.775885,-4590.875692,60.945372,22.121259,0.006414,0.006630,60.945372,0.82621
3,2023-10-25,0.821617,1.009265,0.999742,0.000456,0.817140,-0.361236,0.840779,0.908771,-0.361666,...,-1340.951190,26.220298,-15.673556,-5036.494319,57.108356,11.599227,0.004530,0.004039,57.108356,0.82224
4,2023-10-24,0.822001,1.000000,1.000114,-0.001222,0.816309,-0.417471,0.890398,3.856589,0.416152,...,-108.269295,-120.589823,-121.701270,-5072.852381,50.341368,-8.020535,0.003879,0.003026,50.341368,0.81631

USD/CHF Features shape: (261, 28)

,Date,opt_sine_offset,opt_sine_amp,opt_sine_freq,opt_sine_phase,opt_fourier_offset,opt_fourier_cosamp,opt_fourier_cosfreq,opt_fourier_cosphase,opt_fourier_sinamp,...,ROC1,ROC5,ROC20,WILLIAMS14,RSI14,CMO9,DEMA9,TEMA9,STOCH14,Close
0,2023-10-30,0.894340,1.0,1.000164,-0.000342,0.904730,0.953000,1.037016,0.791203,0.952940,...,-23.655863,-41.774218,857.380917,-4710.024341,53.740042,10.688443,-0.019917,-0.018318,53.740042,0.90311
1,2023-10-27,0.893080,1.0,1.000317,-0.002042,0.904571,-0.021541,0.973717,0.887653,0.022070,...,-10.532684,-28.011242,736.556813,-4731.883381,48.623017,-3.503581,-0.022631,-0.022158,48.623017,0.89883
2,2023-10-26,0.893069,1.0,0.999687,0.003840,0.904474,-1.335103,0.952340,1.278726,-1.336469,...,-15.253890,10.189200,-618.900475,-3989.827839,45.855315,-11.434721,-0.024179,-0.024723,45.855315,0.89670
3,2023-10-25,0.895026,1.0,0.999566,0.001871,0.904390,-0.247967,0.958142,0.955114,-0.248868,...,-9.345522,41.932422,1952.241537,-3286.776417,40.794126,-26.322317,-0.025154,-0.026822,40.794126,0.89306
4,2023-10-24,0.896682,1.0,0.999802,0.001976,0.904346,-0.256868,0.969179,0.513966,-0.256785,...,10.959936,59.989913,443.548175,-3220.193542,37.104654,-37.495271,-0.024549,-0.026957,37.104654,0.89060

EUR/GBP Features shape: (261, 28)

,Date,opt_sine_offset,opt_sine_amp,opt_sine_freq,opt_sine_phase,opt_fourier_offset,opt_fourier_cosamp,opt_fourier_cosfreq,opt_fourier_cosphase,opt_fourier_sinamp,...,ROC1,ROC5,ROC20,WILLIAMS14,RSI14,CMO9,DEMA9,TEMA9,STOCH14,Close
0,2023-10-30,0.871324,1.000000,0.999925,-0.000157,0.866722,0.050466,1.057274,-2.330566,-0.050456,...,-685.458422,-2781.445312,-123.038714,-7108.520456,60.876956,23.387292,0.001447,0.001653,60.876956,0.87155
1,2023-10-27,0.871417,1.000000,1.000040,0.000333,0.866280,-0.148113,1.046202,1.052423,-0.147679,...,-106.833746,-110.987209,-96.793250,-7117.803844,58.739189,17.307058,0.001229,0.001605,58.739189,0.87041
2,2023-10-26,0.870663,1.007848,1.000247,-0.002376,0.865963,-0.192804,1.038589,0.570957,-0.192535,...,339.541437,-188.295080,-149.102799,-7096.631206,66.426068,40.135649,0.001442,0.002261,66.426068,0.87301
3,2023-10-25,0.869772,1.000000,1.000092,0.000016,0.865552,-0.107598,1.049687,0.176491,-0.107937,...,71.056091,-122.359377,-201.350123,-7111.940652,63.191878,31.454873,0.000375,0.001151,63.191878,0.87113
4,2023-10-24,0.868797,1.001678,1.000280,-0.003054,0.865123,0.107448,1.049344,-2.259802,0.107852,...,-991.406250,-105.029090,-109.338107,-7113.813616,62.784618,30.342708,-0.000224,0.000701,62.784618,0.87090

EUR/CHF Features shape: (261, 28)

,Date,opt_sine_offset,opt_sine_amp,opt_sine_freq,opt_sine_phase,opt_fourier_offset,opt_fourier_cosamp,opt_fourier_cosfreq,opt_fourier_cosphase,opt_fourier_sinamp,...,ROC1,ROC5,ROC20,WILLIAMS14,RSI14,CMO9,DEMA9,TEMA9,STOCH14,Close
0,2023-10-30,0.948062,0.994804,1.000328,-0.002938,0.957280,-0.055626,1.115753,-3.608227,-0.054615,...,-15.823834,-25.666413,132.794412,-5349.620116,49.800035,5.291365,-0.028243,-0.026711,49.800035,0.95387
1,2023-10-27,0.946642,0.985391,1.000219,-0.000751,0.957327,0.124506,0.920985,2.226552,0.124387,...,-7.002664,-16.948550,154.770395,-5067.863543,42.976766,-12.556928,-0.030439,-0.029799,42.976766,0.94952
2,2023-10-26,0.946777,0.991940,0.999730,0.001305,0.957654,-0.064898,0.956614,0.622175,0.065183,...,-4.150430,-1.104042,204.738526,-5078.473487,39.333112,-22.439060,-0.031238,-0.031175,39.333112,0.94745
3,2023-10-25,0.947573,1.000000,0.999964,0.001301,0.958014,-0.132092,0.848127,5.509602,-0.131885,...,15.983346,21.417173,238.524447,-4590.213192,37.022508,-28.728855,-0.031217,-0.031558,37.022508,0.94617
4,2023-10-24,0.947763,1.000000,0.999964,0.000231,0.958311,-0.164079,1.079824,-2.845313,0.163681,...,-14.583920,-0.449267,142.386030,-4322.983765,41.948383,-15.803868,-0.030442,-0.030962,41.948383,0.95042

GBP/CHF Features shape: (261, 28)

,Date,opt_sine_offset,opt_sine_amp,opt_sine_freq,opt_sine_phase,opt_fourier_offset,opt_fourier_cosamp,opt_fourier_cosfreq,opt_fourier_cosphase,opt_fourier_sinamp,...,ROC1,ROC5,ROC20,WILLIAMS14,RSI14,CMO9,DEMA9,TEMA9,STOCH14,Close
0,2023-10-30,1.087868,0.995689,1.000483,-0.003326,1.104296,0.324705,1.082650,-2.802933,0.325839,...,-11.644268,-22.706574,339.781622,-3320.818545,43.970261,-7.228970,-0.034674,-0.033152,43.970261,1.09437
1,2023-10-27,1.086111,1.000000,1.000191,-0.001122,1.104868,0.735130,0.887483,3.517272,0.735010,...,-14.698335,-20.903067,413.792867,-3331.619127,39.567122,-18.503116,-0.036957,-0.036686,39.567122,1.09066
2,2023-10-26,1.087234,0.997088,0.999378,0.004446,1.105682,-0.002960,1.247374,-2.644856,0.001491,...,2.188712,19.442829,622.296283,-3347.601660,32.251386,-37.798683,-0.038120,-0.039054,32.251386,1.08517
3,2023-10-25,1.089257,1.000000,0.999847,0.001544,1.106545,0.111644,1.028396,1.319039,0.113049,...,16.511976,38.497724,250.739595,-3193.094257,32.788466,-36.441426,-0.036799,-0.038160,32.788466,1.08597
4,2023-10-24,1.090748,1.002357,0.999585,0.004167,1.107529,0.606325,1.065306,0.615667,0.606521,...,-13.865562,36.746164,258.070548,-3178.721338,36.436717,-27.182013,-0.035171,-0.036933,36.436717,1.09115